# Generated by Django 3.0.4 on 2020-03-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksuggestion',
            old_name='option_explainer',
            new_name='task_explainer',
        ),
        migrations.RenameField(
            model_name='tasksuggestion',
            old_name='option_text',
            new_name='task_text',
        ),
        migrations.RenameField(
            model_name='tasksuggestion',
            old_name='option_voters',
            new_name='task_voters',
        ),
    ]
