# Generated by Django 3.0.4 on 2020-03-22 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tt_core', '0006_auto_20200322_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksuggestion',
            name='task_voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
