# Generated by Django 3.0.4 on 2020-03-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0008_auto_20200324_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_assigned',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
