# Generated by Django 3.0.4 on 2020-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0009_mission_date_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extra_content',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tweak_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
