# Generated by Django 3.0.4 on 2020-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0010_auto_20200328_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='extra_content',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
