# Generated by Django 3.0.4 on 2020-03-28 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0011_auto_20200328_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
