# Generated by Django 3.0.4 on 2020-03-29 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0014_auto_20200328_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksuggestion',
            name='suggestion_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
