# Generated by Django 3.0.4 on 2020-04-02 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tt_core', '0015_tasksuggestion_suggestion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksuggestion',
            name='last_vote',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
